name: Check Youtube Music

on:
  schedule:
    - cron: '43 * * * *'
  workflow_dispatch:

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: API response cache
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-api-cache
          # actions/cache automatically saves this path at the end of the job if it changes.

      - name: Retrieve releases
        run: pnpm retrieve-releases:youtube-music
        env:
          BLUESKY_IDENTIFIER_FOR_YOUTUBE_MUSIC: ${{ vars.BLUESKY_IDENTIFIER_FOR_YOUTUBE_MUSIC }}
          BLUESKY_PASSWORD_FOR_YOUTUBE_MUSIC: ${{ secrets.BLUESKY_PASSWORD_FOR_YOUTUBE_MUSIC }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_FOR_YOUTUBE_MUSIC: ${{ vars.TELEGRAM_CHANNEL_FOR_YOUTUBE_MUSIC }}

      - name: Create a Github Pages post
        run: pnpm create-post
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/youtube-music docs
          git diff --cached --quiet || git commit -m "chore: auto-update youtube music data and docs"
          git pull origin ${{ github.ref_name }} --no-rebase
          git push origin HEAD:${{ github.ref_name }}
